#
#    ██╗░░██╗░█████╗░██████╗░███╗░░░███╗░█████╗░███╗░░██╗░█████╗░░█████╗░░██████╗
#    ██║░██╔╝██╔══██╗██╔══██╗████╗░████║██╔══██╗████╗░██║██╔══██╗██╔══██╗██╔════╝
#    █████═╝░███████║██████╔╝██╔████╔██║███████║██╔██╗██║██║░░╚═╝██║░░██║╚█████╗░
#    ██╔═██╗░██╔══██║██╔══██╗██║╚██╔╝██║██╔══██║██║╚████║██║░░██╗██║░░██║░╚═══██╗
#    ██║░╚██╗██║░░██║██║░░██║██║░╚═╝░██║██║░░██║██║░╚███║╚█████╔╝╚█████╔╝██████╔╝
#    ╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝░╚════╝░░╚════╝░╚═════╝░
#
#    ░██████╗██████╗░██╗███╗░░██╗███╗░░██╗██╗███╗░░██╗
#    ██╔════╝██╔══██╗██║████╗░██║████╗░██║██║████╗░██║
#    ╚█████╗░██████╔╝██║██╔██╗██║██╔██╗██║██║██╔██╗██║
#    ░╚═══██╗██╔═══╝░██║██║╚████║██║╚████║██║██║╚████║
#    ██████╔╝██║░░░░░██║██║░╚███║██║░╚███║██║██║░╚███║
#    ╚═════╝░╚═╝░░░░░╚═╝╚═╝░░╚══╝╚═╝░░╚══╝╚═╝╚═╝░░╚══╝
#


prefijo: "§x§F§B§0§0§0§0§lM§x§D§C§0§0§0§0§lC §x§B§C§0§0§0§0§lE§x§9§D§0§0§0§0§lX§x§7§E§0§0§0§0§lT§x§5§E§0§0§0§0§lR§x§3§F§0§0§0§0§lE§x§1§F§0§0§0§0§lM§x§0§0§0§0§0§0§lO"

mensaje_activado: "§x§A§2§F§B§7§E¡ᴇʟ ᴘᴠᴘ ᴇsᴛᴀ ᴀʜᴏʀᴀ ᴀᴄᴛɪᴠᴏ!"

mensaje_desactivado: "§x§F§B§5§D§5§D¡ᴇʟ ᴘᴠᴘ ᴇsᴛᴀ ᴀʜᴏʀᴀ ᴅᴇsᴀᴄᴛɪᴠᴀᴅᴏ!"

developer: "§7By the Developer ©Spinnin34"

titulo: "§x§F§B§0§0§0§0§lM§x§D§C§0§0§0§0§lC §x§B§C§0§0§0§0§lE§x§9§D§0§0§0§0§lX§x§7§E§0§0§0§0§lT§x§5§E§0§0§0§0§lR§x§3§F§0§0§0§0§lE§x§1§F§0§0§0§0§lM§x§0§0§0§0§0§0§lO"

vidas: "§fᴛɪᴇɴᴇ ᴠɪᴅᴀꜱ ʀᴇꜱᴛᴀɴᴛᴇꜱ:§x§F§B§0§0§7§1"

vidas_restantes: "§x§F§B§4§7§4§7ʜᴀꜱ ᴘᴇʀᴅɪᴅᴏ ᴜɴᴀ ᴠɪᴅᴀ."

ban: "§x§F§B§0§0§7§1ʜᴀꜱ ᴘᴇʀᴅɪᴅᴏ ᴛᴏᴅᴀs ᴛᴜꜱ ᴠɪᴅᴀꜱ. ʜᴀꜱ ꜱɪᴅᴏ ʙᴀɴᴇᴀᴅᴏ."

# Renica el server o haz /reload confirm
# Wiki and info https://karmancos.42web.io/download/mcextremo.html